version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: postgres-admin-site
    environment:
      # POSTGRES_DB: "habrdb"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker_postgres:/docker-entrypoint-initdb.d
      - docker_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  docker_postgres: