psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE admim;
    GRANT ALL PRIVILEGES ON DATABASE admin TO $POSTGRES_USER;
    CREATE DATABASE social_gamification;
    GRANT ALL PRIVILEGES ON DATABASE social_gamification TO $POSTGRES_USER;
    CREATE DATABASE activity;
    GRANT ALL PRIVILEGES ON DATABASE activity TO $POSTGRES_USER;
EOSQL